Revision: 340f486aa0126facb67494449b5c2ee46a1a75e6
Patch-set: 2
File: test/136-daemon-jni-shutdown/daemon_jni_shutdown.cc

43:2-43:22
Wed Jun 08 18:09:41 2016 +0000
Author: Mathieu Chartier <1015378@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 239024ca_3e8349c2
Bytes: 150
If the thread is still running code and another thread calls DestroyJavaVM, I thought it DestroyJavaVM would block until it the threads are suspended?

43:2-43:22
Wed Jun 08 18:24:57 2016 +0000
Author: Alex Light <1047769@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: 239024ca_3e8349c2
UUID: 239024ca_3ec8a9ba
Bytes: 176
If this isn't entered the 'About to call exception check' will never be printed, which causes a fail. Also it seems that by faking up our own stack we can confuse those checks.

