Revision: 9cc7bddb913a6d912f89b6b72ac055f1cb3b165c
Patch-set: 1
File: runtime/mirror/throwable.cc

75:38-75:82
Thu Feb 26 13:21:54 2015 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 22dc672f_fd22479d
Bytes: 41
or stack_state->AsObjectArray<Object>() ?

File: runtime/thread.cc

1630:9-1630:75
Thu Feb 26 13:21:54 2015 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 22dc672f_3dde6fe2
Bytes: 165
It won't work for recursive case (m calls m). I think you need to know the stack depth at the time the exception was thrown and compare with the current stack depth.

1630:9-1630:75
Thu Feb 26 14:21:23 2015 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: 22dc672f_3dde6fe2
UUID: a2b937da_b957ffc1
Bytes: 47
Right, good point. Nevermind the approach then.

