Revision: ec27dc12124d57283d8f86e5386c95896b01eb23
Base-for-patch-set: 4
File: runtime/interpreter/interpreter_common.cc

511:8-511:52
Fri Feb 27 07:36:02 2015 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: c2df0b7e_62f436d8
Bytes: 115
You can't just remove this one. You need to replace with "!self->IsExceptionThrownByCurrentMethod(exception.Get())"

511:8-511:52
Fri Feb 27 10:36:13 2015 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: c2df0b7e_62f436d8
UUID: 42a15b0b_2e06a749
Bytes: 149
As discussed, this code does not seem right, as we are not unwinding here, but just jumping to the catch handler in the current method. I removed it.

File: runtime/quick_exception_handler.cc

162:2-167:3
Fri Feb 27 07:36:02 2015 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 025843e4_e4681add
Bytes: 43
That's the part I expected to be removed :)

